### ISSUE TITLE
Mongock does not executing when using `java -jar` with Spring Boot 3

### ISSUE THREAD

**Issue by mraible** [mongock/mongock-jdk17#6]
On the JHipster project, we noticed that Mongock doesn't execute when running the app with `java -jar target/app.jar`. However, it works just fine when running `mvn spring-boot:run`. We believe this is a bug in Mongock, but maybe we've misconfigured something?

More information at https://github.com/jhipster/generator-jhipster/pull/19791#issuecomment-1320973728.

**Comment by osantana85** [comment]
Hello @mraible , please could you verify if it's related to this known issue with reflections lib? [#472](https://github.com/mongock/mongock/issues/472). It includes a workaround, but we are working to avoid that dependency in short term.

**Comment by mraible** [comment]
I tried the workaround of excluding and downgrading the reflections lib:

```xml
<dependency>
    <groupId>io.mongock</groupId>
    <artifactId>mongock-springboot-v3</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>io.mongock</groupId>
    <artifactId>mongodb-springdata-v4-driver</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.reflections</groupId>
    <artifactId>reflections</artifactId>
    <version>0.9.11</version>
</dependency>
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>mongodb</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-mongodb</artifactId>
</dependency>
<dependency>
    <groupId>io.mongock</groupId>
    <artifactId>mongodb-reactive-driver</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

Now I get a different error:

```
io.mongock.api.exception.MongockException: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2724b593
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:67)
	at io.mongock.runner.springboot.base.MongockApplicationRunner.run(MongockApplicationRunner.java:18)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:748)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at tech.jhipster.sample.SampleWebfluxMongodbApp.main(SampleWebfluxMongodbApp.java:69)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @2724b593
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
	at javassist.util.proxy.FactoryHelper.toClass2(FactoryHelper.java:181)
	at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:164)
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:508)
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:493)
	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:429)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:400)
	at io.mongock.driver.api.lock.guard.proxy.LockGuardProxyFactory.createProxy(LockGuardProxyFactory.java:88)
	at io.mongock.driver.api.lock.guard.proxy.LockGuardProxyFactory.getRawProxy(LockGuardProxyFactory.java:60)
	at io.mongock.runner.core.executor.dependency.DependencyManager.getDependency(DependencyManager.java:52)
	at io.mongock.runner.core.executor.dependency.DependencyManagerWithContext.getDependency(DependencyManagerWithContext.java:40)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.getParameter(ChangeLogRuntimeImpl.java:117)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.getInvokationParameters(ChangeLogRuntimeImpl.java:105)
	at io.mongock.runner.core.executor.ChangeLogRuntimeImpl.getInstance(ChangeLogRuntimeImpl.java:89)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.getChangeLogInstance(MigrateExecutorBase.java:155)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processSingleChangeLog(MigrateExecutorBase.java:134)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processChangeLogs(MigrateExecutorBase.java:126)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.lambda$processMigration$1(MigrateExecutorBase.java:121)
	at io.mongock.runner.core.executor.NonTransactioner.executeInTransaction(NonTransactioner.java:17)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.processMigration(MigrateExecutorBase.java:121)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:103)
	at io.mongock.runner.core.executor.operation.migrate.MigrateExecutorBase.executeMigration(MigrateExecutorBase.java:46)
	at io.mongock.runner.core.executor.MongockRunnerImpl.execute(MongockRunnerImpl.java:53)
	... 10 common frames omitted
```

My Java version:

```
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode)
```

**Comment by osantana85** [comment]
This error is related to the ChangeUnit execution, so the first one was fixed. Could you write complete Mongock's output log to let me identify what ChangeUnit is failing? (in case there are more than one). Then we need to check if there is a problem with the execution method parameters, because Mongock is failing when trying to get a proxy for some of them.

**Comment by mraible** [comment]
It seems strange that I'd have to change anything since it works when it's run via Maven. If I remove the workaround in `pom.xml`:

```xml
<dependency>
    <groupId>io.mongock</groupId>
    <artifactId>mongock-springboot-v3</artifactId>
</dependency>
<dependency>
    <groupId>io.mongock</groupId>
    <artifactId>mongodb-springdata-v4-driver</artifactId>
</dependency>
<dependency>
    <groupId>org.testcontainers</groupId>
    <artifactId>mongodb</artifactId>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-data-mongodb</artifactId>
</dependency>
<dependency>
    <groupId>io.mongock</groupId>
    <artifactId>mongodb-reactive-driver</artifactId>
</dependency>
```

And run `mvn spring-boot:run`, it executes my change unit.

```
2022-11-20T17:57:59.411-07:00  INFO 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Mongock trying to acquire the lock
2022-11-20T17:57:59.422-07:00  INFO 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Mongock acquired the lock until: Sun Nov 20 17:58:59 MST 2022
2022-11-20T17:57:59.422-07:00  INFO 50968 --- [       Thread-4] i.m.driver.core.lock.LockManagerDefault  : Starting mongock lock daemon...
2022-11-20T17:57:59.422-07:00 DEBUG 50968 --- [       Thread-4] i.m.driver.core.lock.LockManagerDefault  : Mongock(daemon) ensuring lock
2022-11-20T17:57:59.423-07:00 DEBUG 50968 --- [       Thread-4] i.m.driver.core.lock.LockManagerDefault  : Mongock trying to refresh the lock
2022-11-20T17:57:59.433-07:00  INFO 50968 --- [  restartedMain] i.m.r.c.e.o.migrate.MigrateExecutorBase  : Mongock starting the data migration sequence id[2022-11-20T17:57:58.929749-195]...
2022-11-20T17:57:59.434-07:00 DEBUG 50968 --- [       Thread-4] i.m.driver.core.lock.LockManagerDefault  : Mongock refreshed the lock until: Sun Nov 20 17:58:59 MST 2022
2022-11-20T17:57:59.434-07:00 DEBUG 50968 --- [       Thread-4] i.m.driver.core.lock.LockManagerDefault  : Calculating millis for lock daemon to sleep
2022-11-20T17:57:59.434-07:00 DEBUG 50968 --- [       Thread-4] i.m.driver.core.lock.LockManagerDefault  : Difference now[Sun Nov 20 17:57:59 MST 2022] and Lock's expiry-date[Sun Nov 20 17:58:59 MST 2022]: 59989ms
2022-11-20T17:57:59.434-07:00 DEBUG 50968 --- [       Thread-4] i.m.driver.core.lock.LockManagerDefault  : Mongock lock daemon sleeping for 19800ms
2022-11-20T17:57:59.452-07:00  INFO 50968 --- [  restartedMain] i.m.r.c.executor.ChangeLogRuntimeImpl    : method[tech.jhipster.sample.config.dbmigrations.InitialSetupMigration] with arguments: [org.springframework.data.mongodb.core.MongoTemplate]
2022-11-20T17:57:59.453-07:00 DEBUG 50968 --- [  restartedMain] i.m.r.c.e.o.migrate.MigrateExecutorBase  : executing changeSet[users-initialization]
2022-11-20T17:57:59.453-07:00  INFO 50968 --- [  restartedMain] i.m.r.c.executor.ChangeLogRuntimeImpl    : method[changeSet] with arguments: []
2022-11-20T17:57:59.453-07:00 DEBUG 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Ensuring the lock
2022-11-20T17:57:59.453-07:00 DEBUG 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Dont need to refresh the lock at[Sun Nov 20 17:57:59 MST 2022], acquired until: Sun Nov 20 17:58:59 MST 2022
2022-11-20T17:57:59.507-07:00 DEBUG 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Ensuring the lock
2022-11-20T17:57:59.507-07:00 DEBUG 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Dont need to refresh the lock at[Sun Nov 20 17:57:59 MST 2022], acquired until: Sun Nov 20 17:58:59 MST 2022
2022-11-20T17:57:59.511-07:00 DEBUG 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Ensuring the lock
2022-11-20T17:57:59.511-07:00 DEBUG 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Dont need to refresh the lock at[Sun Nov 20 17:57:59 MST 2022], acquired until: Sun Nov 20 17:58:59 MST 2022
2022-11-20T17:57:59.533-07:00 DEBUG 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Ensuring the lock
2022-11-20T17:57:59.533-07:00 DEBUG 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Dont need to refresh the lock at[Sun Nov 20 17:57:59 MST 2022], acquired until: Sun Nov 20 17:58:59 MST 2022
2022-11-20T17:57:59.535-07:00 DEBUG 50968 --- [  restartedMain] i.m.r.c.e.o.migrate.MigrateExecutorBase  : successfully executed changeSet[users-initialization]
2022-11-20T17:57:59.535-07:00  INFO 50968 --- [  restartedMain] i.m.r.c.e.o.migrate.MigrateExecutorBase  : APPLIED - {"id"="users-initialization", "type"="execution", "author"="default_author", "class"="InitialSetupMigration", "method"="changeSet"}
2022-11-20T17:57:59.537-07:00 DEBUG 50968 --- [  restartedMain] .m.s.v.r.MongoSync4ChangeEntryRepository : SaveOrUpdate[ChangeEntry{executionId='2022-11-20T17:57:58.929749-195', changeId='users-initialization', author='default_author', timestamp=Sun Nov 20 17:57:59 MST 2022, state=EXECUTED, type=EXECUTION, changeLogClass='tech.jhipster.sample.config.dbmigrations.InitialSetupMigration', changeSetMethod='changeSet', metadata=null, executionMillis=82, executionHostname='NVMF3WCF13'}] with result_[upsertId:BsonObjectId{value=637acd1733533d17277f7019}, matches: 0, modifies: 0, acknowledged: true]
2022-11-20T17:57:59.537-07:00  INFO 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Mongock releasing the lock
2022-11-20T17:57:59.537-07:00  INFO 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Mongock releasing the lock
2022-11-20T17:57:59.540-07:00  INFO 50968 --- [  restartedMain] i.m.driver.core.lock.LockManagerDefault  : Mongock released the lock
2022-11-20T17:57:59.540-07:00  INFO 50968 --- [  restartedMain] i.m.r.c.e.o.migrate.MigrateExecutorBase  : Mongock has finished
```

Here's the code for `InitialSetupMigration`:

```java
package tech.jhipster.sample.config.dbmigrations;

import io.mongock.api.annotations.ChangeUnit;
import io.mongock.api.annotations.Execution;
import io.mongock.api.annotations.RollbackExecution;
import java.time.Instant;
import org.springframework.data.mongodb.core.MongoTemplate;
import tech.jhipster.sample.config.Constants;
import tech.jhipster.sample.domain.Authority;
import tech.jhipster.sample.domain.User;
import tech.jhipster.sample.security.AuthoritiesConstants;

/**
 * Creates the initial database setup.
 */
@ChangeUnit(id = "users-initialization", order = "001")
public class InitialSetupMigration {

    private final MongoTemplate template;

    public InitialSetupMigration(MongoTemplate template) {
        this.template = template;
    }

    @Execution
    public void changeSet() {
        Authority userAuthority = createUserAuthority();
        userAuthority = template.save(userAuthority);
        Authority adminAuthority = createAdminAuthority();
        adminAuthority = template.save(adminAuthority);
        addUsers(userAuthority, adminAuthority);
    }

    @RollbackExecution
    public void rollback() {}

    private Authority createAuthority(String authority) {
        Authority adminAuthority = new Authority();
        adminAuthority.setName(authority);
        return adminAuthority;
    }

    private Authority createAdminAuthority() {
        Authority adminAuthority = createAuthority(AuthoritiesConstants.ADMIN);
        return adminAuthority;
    }

    private Authority createUserAuthority() {
        Authority userAuthority = createAuthority(AuthoritiesConstants.USER);
        return userAuthority;
    }

    private void addUsers(Authority userAuthority, Authority adminAuthority) {
        User user = createUser(userAuthority);
        template.save(user);
        User admin = createAdmin(adminAuthority, userAuthority);
        template.save(admin);
    }

    private User createUser(Authority userAuthority) {
        User userUser = new User();
        userUser.setId("user-2");
        userUser.setLogin("user");
        userUser.setPassword("$2a$10$VEjxo0jq2YG9Rbk2HmX9S.k1uZBGYUHdUcid3g/vfiEl7lwWgOH/K");
        userUser.setFirstName("User");
        userUser.setLastName("User");
        userUser.setEmail("user@localhost");
        userUser.setActivated(true);
        userUser.setLangKey("en");
        userUser.setCreatedBy(Constants.SYSTEM);
        userUser.setCreatedDate(Instant.now());
        userUser.getAuthorities().add(userAuthority);
        return userUser;
    }

    private User createAdmin(Authority adminAuthority, Authority userAuthority) {
        User adminUser = new User();
        adminUser.setId("user-1");
        adminUser.setLogin("admin");
        adminUser.setPassword("$2a$10$gSAhZrxMllrbgj/kkK9UceBPpChGWJA7SYIb1Mqo.n5aNLq1/oRrC");
        adminUser.setFirstName("admin");
        adminUser.setLastName("Administrator");
        adminUser.setEmail("admin@localhost");
        adminUser.setActivated(true);
        adminUser.setLangKey("en");
        adminUser.setCreatedBy(Constants.SYSTEM);
        adminUser.setCreatedDate(Instant.now());
        adminUser.getAuthorities().add(adminAuthority);
        adminUser.getAuthorities().add(userAuthority);
        return adminUser;
    }
}
```

**Comment by osantana85** [comment]
Hello @mraible , we have faced this error in the past, related to have injection via constructor in ChangeUnit in jdk17+. ([issue flamingock/mongock#140](https://github.com/mongock/mongock/issues/534)).
Could you write your `mvn dependency:tree` output to check if there is a problem with another dependency version (probably javassist)?

**Comment by mraible** [comment]
If I run `mvn dependency:tree`, it looks like the correct version of javassist is pulled in.

```
[INFO] +- io.mongock:mongock-springboot-v3:jar:5.2.0:compile
[INFO] |  +- io.mongock:mongock-runner-core:jar:5.1.6:compile
[INFO] |  |  +- io.mongock:mongock-driver-api:jar:5.1.6:compile
[INFO] |  |  |  +- org.javassist:javassist:jar:3.28.0-GA:compile
[INFO] |  |  |  +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |  |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  |  |  |  +- com.google.errorprone:error_prone_annotations:jar:2.11.0:compile
[INFO] |  |  |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  |  |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  +- org.reflections:reflections:jar:0.10.2:compile
[INFO] |  |  |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  +- org.apache.maven:maven-artifact:jar:3.6.1:compile
[INFO] |  |  |  \- org.codehaus.plexus:plexus-utils:jar:3.2.0:compile
[INFO] |  |  \- com.google.code.gson:gson:jar:2.9.1:compile
[INFO] |  +- io.mongock:mongock-api:jar:5.1.6:compile
[INFO] |  \- io.mongock:mongock-utils:jar:5.1.6:compile
```

I'm not sure it's a classpath problem since everything works with `mvn spring-boot:run`.

**Comment by osantana85** [comment]
That dependency tree includes the wrong `org.reflections` version (0.10.2), which was causing the first problem. Did you change the pom and removed the exclusions?

**Comment by mraible** [comment]
You are correct @osantana85. If I use the correct versions of `org.reflections` and `javassist`, everything works!

```xml
<dependency>
    <groupId>io.mongock</groupId>
    <artifactId>mongock-springboot-v3</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>io.mongock</groupId>
    <artifactId>mongodb-springdata-v4-driver</artifactId>
    <exclusions>
        <exclusion>
            <groupId>org.reflections</groupId>
            <artifactId>reflections</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>org.reflections</groupId>
    <artifactId>reflections</artifactId>
    <version>0.9.11</version>
    <exclusions>
        <exclusion>
            <groupId>org.javassist</groupId>
            <artifactId>javassist</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

**Comment by osantana85** [comment]
Cool!

NOTE: Mongock uses `org.reflections` version 0.10.1 (in your pom you are using 0.9.11).
